server:
  address: 172.17.126.107
  port: 8805
  jsp-servlet:
    class-name: org.apache.jasper.servlet.JspServlet
  error:
    whitelabel:
      enabled: true

spring:
  application:
    index: v1.0
    name: smartoa-service-screen
  resources:
    static-locations: classpath:/static/
  primary:  
    datasource:
      name: smartoa
      url: jdbc:mysql://chengxz-db.mysql.rds.aliyuncs.com:3306/smartoa?useUnicode=true&amp;characterEncoding=utf-8
      username: chengxz_admin
      password: Chengxz@20170823@Techhero
      #使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      #filters: stat
      filters: stat,wall,log4j
      maxActive: 5
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 50
      continue-on-error: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  secondary: 
    datasource:
      name: iddc
      url: jdbc:mysql://chengxz-db.mysql.rds.aliyuncs.com:3306/iddc?useUnicode=true&amp;characterEncoding=utf-8
      username: chengxz_admin
      password: Chengxz@20170823@Techhero
      #使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      #filters: stat
      filters: stat,wall,log4j
      maxActive: 500
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 50
      continue-on-error: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 172.17.126.106
    timeout: 0   #代表永不过期
    port: 6379

mybatis:
   configuration:
      mapUnderscoreToCamelCase: true 

#LOG
logging:
  file: /opt/smartoa/logs/smartoa-service-screen.log
  
#大屏ID及权限-产环境不同
screen:
  op:
    data:
      id: 45ad5f395e60366fa4eaba0397ea169f
      token: hlG5eE2UqQsWX83mi5bDl74v4v3LXfFN
    assets:
      id: e2efb3b17d8db4a7f4f9da67a1f0bf35
      token: LFW8_jqpjxbyJ2_6CIf7LmPLZZA1HknO
    heats:
      id: a4556e60a82a4fdcced2d85141c3de2b
      token: 3KFxCp6BW4-Pqxu0g5YAJJssYWXB9FuW
  servicer:
    data:
      id: 9ab5e1ad583d35b08e35dd248bc27424
      token: Lq-EM6I6kObz9BNcW2o3I7BC7GjTLUOA
    assets:
      id: 48bc3a1ebf33c1ea399e139953643e20
      token: Jn45Qsfi75NWNwxVpURlP6KraC478D4F
    heats:
      id: 9931ad78cf8bcf38a6425a3c73e03a6f
      token: T9wWtXzNTPxNk3-xhfbaFZTmzbmc3L7N
    schedule:
      id: 198d03779c8583159358ea135fc78af0
      token: TN6P9l9vUxTdjDuMXeagkq4FXKA5RtZd
  