server:
  address: 172.17.126.105
  port: 8805
  jsp-servlet:
    class-name: org.apache.jasper.servlet.JspServlet
  error:
    whitelabel:
      enabled: true

spring:
  application:
    index: v1.0
    name: smartoa-service-screen
  resources:
    static-locations: classpath:/static/
  primary:  
    datasource:
      name: smartoa
      url: jdbc:mysql://172.17.126.104:3306/smartoa?useUnicode=true&amp;characterEncoding=utf-8
      username: root
      password: 123456
      #使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      #filters: stat
      filters: stat,wall,log4j
      maxActive: 500
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 50
      continue-on-error: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  secondary: 
    datasource:
      name: iddc
      url: jdbc:mysql://172.17.126.104:3306/iddc?useUnicode=true&amp;characterEncoding=utf-8
      username: root
      password: 123456
      #使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      #filters: stat
      filters: stat,wall,log4j
      maxActive: 500
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 50
      continue-on-error: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 172.17.126.104
    timeout: 0   #代表永不过期
    port: 6379

mybatis:
   configuration:
      mapUnderscoreToCamelCase: true 

#LOG
logging:
 #config: classpath:log4j2.xml
 #file: /cnpserver/provider/log.log
  file: /opt/smartoa/logs/smartoa-service-screen.log
  

#大屏ID及权限（注，测试与生产环境不同）
screen:
  op:
    data:
      id: 330fffb5bd2e36e04b5ae857677e3e09
      token: uaDLbNSrBQjHQTtxFJm4FAXVmTsf-EX4
    assets:
      id: 86f1dad243fef872d2b69efdcea2f749
      token: HjWcHGHDMH_QVDFMu0J_V0ccFH12iZje
    heats:
      id: feed382b06dcbd022f0d8f23e4c1296a
      token: AT0bkgCcJz-QxKvBq6WX1QeVZDKr7D6L
  servicer:
    data:
      id: 9f818c15fffcc1b6a3022312725869f8
      token: Qk5nXE45ux-jY-Gw3iNCgjNharWgd5n_
    assets:
      id: 1c9df6ae697114298b0a9ef960751bbb
      token: Bm-U1NYIajcyyTC02tcj7wJZ3ApVndgj
    heats:
      id: db7acb86398a13286d282f4386cef027
      token: -6IxC8YRk1BAZULzYzX6ZgXE48gOKKd_
    schedule:
      id: 971ccdd8a76428320b35d466ce718e5b
      token: rIqKTabP9dGbK4x-G0jL4wUBy-PWv9O7
